import type { Recipe } from './types'

export const MOCK_RECIPES: Recipe[] = [
  {
    id: '1',
    title: 'Tortilla de patatas',
    description:
      'Clásica tortilla española con huevos, patatas y cebolla. Dorada por fuera y jugosa por dentro, perfecta para compartir en tapas o como plato principal.',
    timeMinutes: 30,
    difficulty: 'Fácil',
    servings: 4,
    timePrepMinutes: 10,
    timeCookMinutes: 20,
    imageUrl: 'https://picsum.photos/seed/tortilla/1200/600',
    ingredients: [
      '6 huevos tamaño L',
      '700 g de patatas (agria o monalisa)',
      '1 cebolla mediana (opcional)',
      'Aceite de oliva suave para freír (aprox. 300 ml)',
      'Sal fina',
      'Pimienta negra recién molida (opcional)',
    ],
    steps: [
      'Pelar y cortar las patatas en láminas finas; picar la cebolla.',
      'Freír patatas y cebolla en aceite de oliva a fuego medio hasta ablandar.',
      'Escurrir y salar; batir los huevos con una pizca de sal y pimienta.',
      'Mezclar patata/cebolla con el huevo y reposar 2-3 minutos.',
      'Cuajar en sartén antiadherente por ambos lados hasta el punto deseado.',
    ],
  },
  {
    id: '2',
    title: 'Pasta al pesto',
    description:
      'Pasta corta o larga con pesto de albahaca casero, cremoso y aromático. Lista en minutos y perfecta para diario.',
    timeMinutes: 20,
    difficulty: 'Fácil',
    servings: 2,
    timePrepMinutes: 8,
    timeCookMinutes: 12,
    imageUrl: 'https://picsum.photos/seed/pesto/1200/600',
    ingredients: [
      '200 g de pasta (spaghetti o fusilli)',
      '40-50 hojas de albahaca fresca',
      '30 g de piñones (o nueces)',
      '40 g de parmesano o grana padano',
      '1 diente de ajo pequeño',
      '60 ml de aceite de oliva virgen extra',
      'Sal y un chorrito del agua de cocción',
    ],
    steps: [
      'Cocer la pasta en abundante agua con sal hasta al dente.',
      'Triturar albahaca, piñones, ajo y parmesano; emulsionar con el aceite.',
      'Ajustar de sal y afinar con agua de cocción hasta textura cremosa.',
      'Mezclar la pasta escurrida con el pesto fuera del fuego y servir.',
    ],
  },
  {
    id: '3',
    title: 'Pollo al horno con verduras',
    description:
      'Muslos de pollo asados lentamente con verduras y romero. Piel crujiente, carne jugosa y jugos para mojar pan.',
    timeMinutes: 55,
    difficulty: 'Media',
    servings: 3,
    timePrepMinutes: 10,
    timeCookMinutes: 45,
    imageUrl: 'https://picsum.photos/seed/pollo/1200/600',
    ingredients: [
      '4 muslos de pollo (con piel)',
      '2 zanahorias',
      '3 patatas medianas',
      '1 cebolla grande',
      '2 dientes de ajo',
      '1 limón (opcional)',
      'Romero y tomillo',
      'Sal, pimienta y aceite de oliva',
    ],
    steps: [
      'Precalentar el horno a 200°C.',
      'Cortar verduras en trozos; disponer con el pollo en bandeja.',
      'Aliñar con aceite, sal, pimienta, hierbas y rodajas de limón.',
      'Hornear 45-55 minutos, girando a mitad, hasta dorar y cocinar por completo.',
    ],
  },
  {
    id: '4',
    title: 'Pollo al horno con verduras',
    description:
      'Muslos de pollo asados lentamente con verduras y romero. Piel crujiente, carne jugosa y jugos para mojar pan.',
    timeMinutes: 55,
    difficulty: 'Media',
    servings: 3,
    timePrepMinutes: 10,
    timeCookMinutes: 45,
    imageUrl: 'https://picsum.photos/seed/pollo/1200/600',
    ingredients: [
      '4 muslos de pollo (con piel)',
      '2 zanahorias',
      '3 patatas medianas',
      '1 cebolla grande',
      '2 dientes de ajo',
      '1 limón (opcional)',
      'Romero y tomillo',
      'Sal, pimienta y aceite de oliva',
    ],
    steps: [
      'Precalentar el horno a 200°C.',
      'Cortar verduras en trozos; disponer con el pollo en bandeja.',
      'Aliñar con aceite, sal, pimienta, hierbas y rodajas de limón.',
      'Hornear 45-55 minutos, girando a mitad, hasta dorar y cocinar por completo.',
    ],
  },
  {
    id: '5',
    title: 'Pollo al horno con verduras',
    description:
      'Muslos de pollo asados lentamente con verduras y romero. Piel crujiente, carne jugosa y jugos para mojar pan.',
    timeMinutes: 55,
    difficulty: 'Media',
    servings: 3,
    timePrepMinutes: 10,
    timeCookMinutes: 45,
    imageUrl: 'https://picsum.photos/seed/pollo/1200/600',
    ingredients: [
      '4 muslos de pollo (con piel)',
      '2 zanahorias',
      '3 patatas medianas',
      '1 cebolla grande',
      '2 dientes de ajo',
      '1 limón (opcional)',
      'Romero y tomillo',
      'Sal, pimienta y aceite de oliva',
    ],
    steps: [
      'Precalentar el horno a 200°C.',
      'Cortar verduras en trozos; disponer con el pollo en bandeja.',
      'Aliñar con aceite, sal, pimienta, hierbas y rodajas de limón.',
      'Hornear 45-55 minutos, girando a mitad, hasta dorar y cocinar por completo.',
    ],
  },
]


